server:
  port: 8080

spring:
  application:
    name: hexagonal-mybatis
  
  # Configuração do DataSource (H2 em memória)
  datasource:
    url: jdbc:h2:mem:hexagonaldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # Console do H2 (para debug no navegador)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration


# MyBatis (esta parte é aninhada diretamente sob o nome da biblioteca, e não sob 'spring')
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.pietro.hexagonal_mybatis.adapters.outbound.persistence.entities
    configuration:
        map-underscore-to-camel-case: true

    